// This file is generated by build-vercel.js
// Placeholder to satisfy Vercel's function detection
export default async function handler(req, res) {
  return res.status(500).json({ error: 'Build not completed' });
}

